version: "3.9"
services:
  hummingbot:
    container_name: hummingbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/home/hummingbot/conf
      - ./conf/connectors:/home/hummingbot/conf/connectors
      - ./conf/strategies:/home/hummingbot/conf/strategies
      - ./logs:/home/hummingbot/logs
      - ./data:/home/hummingbot/data
      - ./scripts:/home/hummingbot/scripts
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    #  environment:
    #    - CONFIG_PASSWORD=a
    #    - CONFIG_FILE_NAME=simple_pmm_example.py
    #    - SCRIPT_CONFIG=conf_simple_pmm_example.yaml

  # gateway:
  #  container_name: gateway
  #  image: hummingbot/gateway:latest
  #  ports:
  #    - "15888:15888"
  #    - "8080:8080"
  #  volumes:
  #    - "./gateway_files/conf:/home/gateway/conf"
  #    - "./gateway_files/logs:/home/gateway/logs"
  #    - "./gateway_files/db:/home/gateway/db"
  #    - "./certs:/home/gateway/certs"
  #  environment:
  #    - GATEWAY_PASSPHRASE=a
