paths:
  /amm/trade:
    post:
      tags:
        - 'amm'
      summary: 'Perform a trade on an AMM'
      operationId: 'trade'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/TradeRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/TradeResponse'

  /amm/price:
    post:
      tags:
        - 'amm'
      summary: 'Get the price for a quote base pair on an AMM'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/PriceRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/PriceResponse'
