paths:
  /avalanche:
    get:
      tags:
        - 'avalanche'
      summary: 'View the Avalanche network and RPC URL that gateway is configured to use'
      description: 'The user can change this by editing src/chains/avalanche/avalanche.config.ts'
      operationId: 'root'
      produces:
        - 'application/json'
      responses:
        '200':
          description: 'Avalanche config'
          schema:
            $ref: '#/definitions/EthereumConfigResponse'

  /avalanche/nonce:
    post:
      tags:
        - 'avalanche'
      summary: 'Get the nonce for the provided Avalanche private key'
      operationId: 'nonce'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumNonceRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumNonceResponse'

  /avalanche/allowances:
    post:
      tags:
        - 'avalanche'
      summary: 'Get the ERC20 allowances for a spender on a given private key'
      operationId: 'allowances'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumAllowancesRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumAllowancesResponse'

  /avalanche/balances:
    post:
      tags:
        - 'avalanche'
      summary: 'Get the balances of an Avalanche private key'
      operationId: 'balances'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumBalancesRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumBalancesResponse'

  /avalanche/approve:
    post:
      tags:
        - 'avalanche'
      summary: 'Create an ERC20 approval for a spender on an Avalanche private key'
      operationId: 'approve'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumApproveRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumApproveResponse'

  /avalanche/poll:
    post:
      tags:
        - 'avalanche'
      summary: 'Poll the status of an Avalanche transaction'
      operationId: 'poll'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumPollRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumPollResponse'

  /avalanche/cancel:
    post:
      tags:
        - 'avalanche'
      summary: 'Cancel Avalanche transaction'
      operationId: 'cancel'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            $ref: '#/definitions/EthereumCancelRequest'
      responses:
        '200':
          schema:
            $ref: '#/definitions/EthereumCancelResponse'
  
