paths:
  /clob:
    get:
      tags:
        - 'clob'
      summary: 'Verify Clob Routes Status'
      description: 'Verify if the Clob routes are ready to use and show some other useful information. '
      operationId: 'clob.root'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/SerumRootRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/SerumRootResponse'
  /clob/markets:
    get:
      tags:
        - 'clob'
      summary: 'Get the markets for a clob'
      operationId: 'markets'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
             $ref: '#/definitions/ClobMarketsRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobMarketResponse'
        '404':
          description: 'Not found response.'
  /clob/orderBook:
    get:
      tags:
        - 'clob'
      summary: 'Gets orderbook for a market'
      operationId: 'orderBook'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
             $ref: '#/definitions/ClobOrderbookRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobOrderbookResponse'
        '404':
          description: 'Not found response.'
  /clob/ticker:
    get:
      tags:
        - 'clob'
      summary: 'Get One or More Tickers'
      description: 'Get the information of one, several or all available tickers.'
      operationId: 'tickers'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
             $ref: '#/definitions/ClobTickerRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobTickerResponse'
        '404':
          description: 'Not found response.'
  /clob/orders:
    post:
      tags:
        - 'clob'
      summary: 'Create One Or More Orders'
      description: 'Create one or more orders.'
      operationId: 'postOrders'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/ClobPostOrderRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobPostOrderResponse'
        '400':
          description: 'Bad request response.'
    get:
      tags:
        - 'clob'
      summary: 'Get One Or More Orders'
      description: 'Get the information of one, several or all orders.'
      operationId: 'orders'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
             $ref: '#/definitions/ClobGetOrderRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobGetOrderResponse'
        '400':
          description: 'Bad request response.'
        '404':
          description: 'Not found response.'
    delete:
      tags:
        - 'clob'
      summary: 'Cancel One Or More Orders Open Orders'
      description: 'Cancel one, several or all open orders.'
      operationId: 'deleteOrders'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/ClobDeleteOrderRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobDeleteOrderResponse'
        '400':
          description: 'Bad request response.'
        '404':
          description: 'Not found response.'
  /clob/batchOrders:
    post:
      tags:
        - 'clob'
      summary: 'Batch create or delete orders'
      description: 'Create or delete orders in batch.'
      operationId: 'batchOrders'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/ClobBatchOrdersRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/ClobBatchOrdersResponse'
        '400':
          description: 'Bad request response.'

  /clob/orders/open:
    get:
      tags:
        - 'clob'
      summary: 'Get One Or More Open Orders'
      description: 'Get the information of one, several or all open orders.'
      operationId: 'clob.getOpenOrders'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/SerumGetOpenOrdersRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/SerumGetOpenOrdersResponse'
        '400':
          description: 'Bad request response.'
        '404':
          description: 'Not found response.'
  /clob/orders/filled:
    get:
      tags:
        - 'clob'
      summary: 'Get One Or More Filled Orders'
      description: 'Get the information of one, several or all filled orders.'
      operationId: 'clob.getFilledOrders'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/SerumGetFilledOrdersRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/SerumGetFilledOrdersResponse'
        '400':
          description: 'Bad request response.'
        '404':
          description: 'Not found response.'
  /clob/settleFunds:
    get:
      tags:
        - 'clob'
      summary: 'Settle Funds of One or More Markets'
      description: 'Settle funds of one, several or all markets.'
      operationId: 'clob.settleFunds'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Request body.'
          required: true
          schema:
            $ref: '#/definitions/SerumPostSettleFundsRequest'
      responses:
        '200':
          description: 'Successful response.'
          schema:
            $ref: '#/definitions/SerumPostSettleFundsResponse'
        '400':
          description: 'Bad request response.'
        '404':
          description: 'Not found response.'
  /clob/estimateGas:
     post:
       tags:
         - 'clob'
       summary: 'Estimate the total gas costs for sending an clob order'
       operationId: 'estimateGas'
       consumes:
         - 'application/json'
       produces:
         - 'application/json'
       parameters:
         - in: 'body'
           name: 'body'
           required: true
           schema:
             $ref: '#/definitions/NetworkSelectionRequest'
       responses:
         '200':
           schema:
             $ref: '#/definitions/EstimateGasResponse'
