name: hummingbot
channels:
  - conda-forge
  - conda-canary
  - defaults
dependencies:
  - coverage=5.5
  - lz4-c=1.9.3
  - lzo=2.10
  - nomkl=1.0
  - nose=1.3.7
  - pandas=1.2.1
  - pip=21.1.2
  - prompt_toolkit=3.0.20
  - pytables=3.6.1
  - python=3.8.2
  - snappy=1.1.7
  - sqlalchemy=1.3.13
  - tzlocal=2.0.0
  - ujson=1.35
  - zstd=1.5
  - pip:
    - 0x-contract-wrappers==2.0.0
    - aioconsole==0.1.15
    - aiohttp==3.7.4.post0
    - aioresponses==0.7.2
    - aiokafka==0.5.2
    - attrdict==2.0.1
    - cachetools==4.0.0
    - coincurve==13.0.0
    - cython==3.0a7
    - diff-cover==5.1.2
    - eth-bloom==1.0.4
    - ethsnarks-loopring==0.1.5
    - flake8==3.7.9
    - idna-ssl==1.1.0
    - objgraph==3.5.0
    - pre-commit==2.1.1
    - psutil==5.7.2
    - pyinstall==0.1.4
    - pyjwt==1.7.1
    - pyperclip==1.7.0
    - python-binance==0.7.5
    - python-telegram-bot==12.4.2
    - rsa==4.7
    - ruamel-yaml==0.16.10
    - signalr-client-aio==0.0.1.6.2
    - simplejson==3.17.2
    - web3==5.23.0
    - websockets==9.1
    - git+https://github.com/CoinAlpha/python-signalr-client.git
prefix: /home/paul/anaconda3/envs/hummingbot
