name: hummingbot-dist
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_0
  - blas=1.0=mkl
  - blosc=1.15.0=hd408876_0
  - bzip2=1.0.6=h14c3975_5
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29=py36_0
  - cffi=1.12.1=py36h2e261b9_0
  - cryptography=2.5=py36h1ba5d50_0
  - cython=0.29.5=py36he6710b0_0
  - hdf5=1.10.4=hb1b8bf9_0
  - idna=2.8=py36_0
  - intel-openmp=2019.1=144
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - lzo=2.10=h49e0be7_2
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - numexpr=2.6.9=py36h9e4a6bb_0
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - openssl=1.1.1b=h7b6447c_0
  - pandas=0.24.1=py36he6710b0_0
  - pip=19.0.3=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.3.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - pytables=3.4.4=py36h71ec239_0
  - python=3.6.7=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=18.0.0=py36he6710b0_0
  - readline=7.0=h7b6447c_5
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_0
  - snappy=1.1.7=hbae5bb6_3
  - sqlalchemy=1.2.18=py36h7b6447c_0
  - sqlite=3.26.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tzlocal=1.5.1=py36_0
  - ujson=1.35=py36h14c3975_0
  - urllib3=1.24.1=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - 0x-contract-addresses==2.0.1
    - 0x-contract-artifacts==2.0.0
    - 0x-json-schemas==1.0.0
    - 0x-order-utils==1.1.1
    - 0x-web3==4.8.2.1
    - aioconsole==0.1.13
    - aiohttp==3.5.4
    - aiokafka==0.5.0
    - async-timeout==3.0.1
    - attrdict==2.0.1
    - attrs==18.2.0
    - autobahn==19.2.1
    - automat==0.7.0
    - chardet==3.0.4
    - constantly==15.1.0
    - cytoolz==0.9.0.1
    - dateparser==0.7.1
    - eth-abi==1.3.0
    - eth-account==0.3.0
    - eth-hash==0.2.0
    - eth-keyfile==0.5.1
    - eth-keys==0.2.1
    - eth-rlp==0.1.2
    - eth-typing==2.0.0
    - eth-utils==1.4.1
    - hexbytes==0.1.0
    - hyperlink==18.0.0
    - idna-ssl==1.1.0
    - incremental==17.5.0
    - kafka-python==1.4.4
    - lru-dict==1.1.6
    - multidict==4.5.2
    - parsimonious==0.8.1
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.4
    - pycryptodome==3.7.3
    - pyhamcrest==1.9.0
    - pyperclip==1.7.0
    - python-binance==0.7.1
    - regex==2019.2.21
    - requests==2.21.0
    - rlp==1.1.0
    - ruamel.yaml==0.15.89
    - service-identity==18.1.0
    - tables==3.4.4
    - toolz==0.9.0
    - twisted==18.9.0
    - txaio==18.8.1
    - typing-extensions==3.7.2
    - web3==4.8.3
    - websockets==6.0
    - yarl==1.3.0
    - zope.interface==4.6.0
prefix: /home/martin_kou/anaconda3/envs/hummingbot
