name: hummingbot
channels:
  - conda-forge
  - defaults
dependencies:
  - aiounittest=1.4.1
  - bidict
  - coverage=5.5
  - gql
  - nomkl=1.0
  - nose=1.3.7
  - nose-exclude
  - numpy=1.20.1
  - numpy-base=1.20.1
  - pandas=1.2.1
  - pip=21.1.2
  - prompt_toolkit=3.0.20
  - pydantic=1.9
  - pytables=3.6.1
  - python=3.8.2
  - scipy=1.6.2
  - sqlalchemy=1.4
  - tabulate==0.8.9
  - typing-extensions<4.6.0
  - ujson=1.35
  - zlib=1.2.11
  - pip:
    - 0x-contract-addresses==3.0.0
    - 0x-contract-wrappers==2.0.0
    - 0x-order-utils==4.0.0
    - aiohttp==3.*
    - aiokafka==0.7.1
    - aioprocessing==2.0.0
    - aioresponses
    - appdirs==1.4.3
    - async-timeout
    - asyncssh==2.7.2
    - appnope==0.1.3
    - base58==2.1.1
    - cachetools==4.0.0
    - commlib-py==0.10.6
    - cryptography==3.4.7
    - cython==3.0a7
    - diff-cover==5.1.2
    - docker==5.0.3
    - dydx-v3-python==2.0.1
    - ethsnarks-loopring==0.1.5
    - flake8==3.7.9
    - importlib-metadata==0.23
    - injective-py==0.6.0.7
    - mypy-extensions==0.4.3
    - pandas_ta==0.3.14b
    - yarl==1.*
    - pre-commit==2.18.1
    - psutil==5.7.2
    - ptpython==3.0.20
    - pyjwt==1.7.1
    - pyperclip==1.7.0
    - pytest==4.6.11
    - python-telegram-bot==12.4.2
    - requests==2.*
    - rsa==4.7
    - ruamel-yaml==0.16.10
    - signalr-client-aio==0.0.1.6.2
    - simplejson==3.17.2
    - substrate-interface==1.6.2
    - solders==0.1.4
    - web3==5.*
    - websockets==9.1
    - git+https://github.com/CoinAlpha/python-signalr-client.git