name: hummingbot
channels:
  - conda-forge
  - defaults
dependencies:
  - aiounittest=1.4.1
  - bidict
  - certifi=2021.5.30
  - coverage=5.5
  - nose=1.3.7
  - nose-exclude
  - numpy=1.20.1
  - numpy-base=1.20.1
  - pandas=1.2.1
  - pip=21.1.2
  - prompt_toolkit=3.0.20
  - pydantic=1.9
  - pytables=3.6.1
  - python=3.8.2
  - scipy=1.6.2
  - six=1.14.0
  - sqlalchemy=1.4
  - sqlite=3.31.1
  - tabulate==0.8.9
  - tzlocal=2.0.0
  - ujson=1.35
  - zlib=1.2.11
  - pip:
    - aiohttp==3.7.4.post0
    - aiokafka==0.7.1
    - aioprocessing==2.0.0
    - aioresponses==0.7.2
    - appdirs==1.4.3
    - async-timeout==3.0.1
    - asyncssh==2.7.2
    - cachetools==4.0.0
    - commlib-py==0.10.6
    - cryptography==2.8
    - cython==3.0a7
    - docker==5.0.3
    - dydx-v3-python==1.0.10
    - ethsnarks-loopring==0.1.5
    - flake8==3.7.9
    - injective-py>=0.5.9.3
    - pandas_ta==0.3.14b
    - pre-commit==2.18.1
    - psutil==5.7.2
    - ptpython==3.0.20
    - pyperclip==1.7.0
    - pytest==4.6.11
    - python-telegram-bot==12.4.2
    - requests==2.22.0
    - rsa==4.7
    - ruamel-yaml==0.16.10
    - signalr-client-aio==0.0.1.6.2
    - setuptools==50.3.2
    - solders==0.1.4
    - web3==5.23.0
    - websockets==9.1
    - yarl==1.4.2
prefix: /home/paul/anaconda3/envs/hummingbot
