name: hummingbot
channels:
  - bioconda
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - blas=1.0=mkl
  - blosc=1.15.0=hd9629dc_0
  - bzip2=1.0.6=h1de35cc_5
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36hb5b8e2f_1
  - cryptography=2.6.1=py36ha12b0ac_0
  - cython=0.29.5=py36h0a44026_0
  - hdf5=1.10.4=hfa1e0ec_0
  - idna=2.8=py36_0
  - intel-openmp=2019.3=199
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=1
  - libgfortran=3.0.1=h93005f0_2
  - libsodium=1.0.16=h3efe00b_0
  - lzo=2.10=h362108e_2
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py36h5e564d8_0
  - mkl_random=1.0.2=py36h27c97d8_0
  - ncurses=6.1=h0a44026_1
  - nose=1.3.7=py36_2
  - numexpr=2.6.9=py36h7413580_0
  - numpy=1.16.2=py36hacdab7b_0
  - numpy-base=1.16.2=py36h6575580_0
  - openssl=1.1.1b=h1de35cc_1
  - pandas=0.24.2=py36h0a44026_0
  - pip=19.0.3=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.3.1=py36_0
  - pyopenssl=19.0.0=py36_0
  - pysocks=1.6.8=py36_0
  - pytables=3.5.1=py36h5bccee9_0
  - python=3.6.7=haf84260_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=5.1=py36h1de35cc_0
  - pyzmq=18.0.0=py36h0a44026_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.8.0=py36_0
  - six=1.12.0=py36_0
  - snappy=1.1.7=he62c110_3
  - sqlalchemy=1.3.1=py36h1de35cc_0
  - sqlite=3.27.2=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tzlocal=1.5.1=py36_0
  - ujson=1.35=py36h1de35cc_0
  - urllib3=1.24.1=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.3.1=h0a44026_3
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - 0x-contract-addresses==2.0.1
    - 0x-contract-artifacts==2.0.0
    - 0x-json-schemas==1.0.0
    - 0x-order-utils==1.1.1
    - 0x-web3==4.8.2.1
    - aioconsole==0.1.14
    - aiohttp==3.6.1
    - aiokafka==0.5.1
    - altgraph==0.16.1
    - appdirs==1.4.3
    - aspy-yaml==1.3.0
    - async-timeout==3.0.1
    - attrdict==2.0.1
    - attrs==19.1.0
    - autobahn==19.3.3
    - automat==0.7.0
    - cachetools==3.0.0
    - cfgv==2.0.1
    - chardet==3.0.4
    - coincurve==12.0.0
    - constantly==15.1.0
    - cytoolz==0.9.0.1
    - dateparser==0.7.1
    - entrypoints==0.3
    - eth-abi==1.3.0
    - eth-account==0.3.0
    - eth-hash==0.2.0
    - eth-keyfile==0.5.1
    - eth-keys==0.2.1
    - eth-rlp==0.1.2
    - eth-typing==2.1.0
    - eth-utils==1.4.1
    - flake8==3.7.8
    - future==0.18.0
    - hexbytes==0.1.0
    - https://hummingbot-python.s3-us-west-2.amazonaws.com/hummingsim-20191212.1-cp36-cp36m-macosx_10_7_x86_64.whl
    - hyperlink==18.0.0
    - hypothesis==4.14.2
    - identify==1.4.7
    - idna-ssl==1.1.0
    - importlib-metadata==0.23
    - importlib-resources==1.0.2
    - incremental==17.5.0
    - jsonschema==3.0.1
    - kafka-python==1.4.3
    - lru-dict==1.1.6
    - macholib==1.11
    - mccabe==0.6.1
    - mock==3.0.5
    - more-itertools==7.2.0
    - multidict==4.5.2
    - mypy-extensions==0.4.1
    - nodeenv==1.3.3
    - parsimonious==0.8.1
    - pre-commit==1.18.2
    - py-ecc==1.7.0
    - pyasn1==0.4.5
    - pyasn1-modules==0.2.4
    - pycodestyle==2.5.0
    - pycryptodome==3.8.0
    - pyflakes==2.1.1
    - pyhamcrest==1.9.0
    - pyinstaller==3.5
    - PyJWT==1.7.1
    - pyperclip==1.7.0
    - pyrsistent==0.14.11
    - python-binance==0.7.1
    - python-telegram-bot==11.1.0
    - regex==2019.3.12
    - requests==2.21.0
    - rlp==1.1.0
    - ruamel-yaml==0.15.89
    - service-identity==18.1.0
    - stringcase==1.2.0
    - toml==0.10.0
    - toolz==0.9.0
    - twisted==18.9.0
    - txaio==18.8.1
    - typing-extensions==3.7.2
    - virtualenv==16.7.5
    - web3==4.8.2
    - websockets==6.0
    - yarl==1.3.0
    - zipp==0.6.0
    - zope-interface==4.6.0
    - git+https://github.com/CoinAlpha/python-signalr-client.git
prefix: /Users/martin_kou/anaconda3/envs/hummingbot
