name: hummingbot
channels:
  - conda-forge
  - defaults
dependencies:
  - bidict
  - coinbase-advanced-py
  - coverage
  - cython=3.0
  - nomkl
  - nose=1.3.7
  - nose-exclude
  - numpy=1.23.5
  - numpy-base=1.23.5
  - pandas=1.5.3
  - pip
  - prompt_toolkit=3.0.20
  - pydantic=1.10
  - pytest
  - python=3.10
  - scipy=1.10.1
  - sqlalchemy=1.4
  - tabulate==0.8.9
  - ujson
  - zlib
  - pip:
    - aiohttp==3.*
    - aioprocessing==2.0
    - aioresponses
    - aiounittest
    - appdirs==1.4.3
    - async-timeout
    - asyncssh==2.13.1
    - pyOpenSSL==21.0.0
    - appnope==0.1.3
    - base58==2.1.1
    - cachetools==4.0.0
    - commlib-py==0.10.6
    - cryptography==3.4.7
    - diff-cover
    - docker==5.0.3
    - eth_abi==4.0.0
    - eth-account==0.8.0
    - eth-utils==2.2.0
    - eip712-structs==1.1.0
    - dotmap==1.3.30
    - flake8==3.7.9
    - gql
    - grpcio-tools
    - importlib-metadata==0.23
    - jsonpickle==3.0.1
    - mypy-extensions==0.4.3
    - msgpack
    - pandas_ta==0.3.14b
    - pre-commit==2.18.1
    - psutil==5.7.2
    - ptpython==3.0.20
    - pyjwt==2.8.0
    - pyperclip==1.7.0
    - python-telegram-bot==12.8
    - requests==2.*
    - rsa==4.7
    - ruamel-yaml==0.16.10
    - signalr-client-aio==0.0.1.6.2
    - substrate-interface==1.6.2
    - solders==0.1.4
    - vega-python-sdk==0.1.3
    - v4_proto
    - web3
    - websockets
    - yarl==1.*
    - git+https://github.com/CoinAlpha/python-signalr-client.git
    - git+https://github.com/konichuvak/dydx-v3-python.git@web3
    - xrpl-py
