name: hummingbot
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.16.3=h7bd577a_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - cython=0.29.15=py38ha925a31_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2020.0=166
  - lz4-c=1.8.1.2=h2fa13f4_0
  - lzo=2.10=h6df0209_2
  - mkl=2020.0=166
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.0.15=py38h14836fe_0
  - mkl_random=1.1.0=py38hf9181ef_0
  - mock=4.0.1=py_0
  - nose=1.3.7=py38_2
  - numexpr=2.7.1=py38h25d0782_0
  - numpy=1.18.1=py38h93ca92e_0
  - numpy-base=1.18.1=py38hc3f5095_1
  - openssl=1.1.1d=he774522_4
  - pandas=1.0.1=py38h47e9c7a_0
  - pip=20.0.2=py_2
  - prompt_toolkit=3.0.3=py_0
  - pygments=2.5.2=py_0
  - pytables=3.6.1=py38ha5be198_0
  - python=3.8.2=h5fd99cc_4_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2019.3=py_0
  - setuptools=45.3.0=py38_0
  - six=1.14.0=py38_0
  - snappy=1.1.7=h777316e_3
  - sqlalchemy=1.3.13=py38he774522_0
  - sqlite=3.30.1=hfa6e2cd_0
  - tzlocal=2.0.0=py38_0
  - ujson=1.35=py38he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py_1
  - wincertstore=0.2=py38_1003
  - xz=5.2.4=h2fa13f4_4
  - zlib=1.2.11=h62dcd97_3
  - zstd=1.3.7=h508b16e_0
  - pip:
    - 0x-contract-addresses==3.0.0
    - 0x-contract-artifacts==2.0.0
    - 0x-contract-wrappers==2.0.0
    - 0x-json-schemas==2.1.0
    - 0x-order-utils==4.0.0
    - aioconsole==0.1.15
    - aiohttp==3.6.2
    - aiokafka==0.5.2
    - altgraph==0.17
    - appdirs==1.4.3
    - asn1crypto==1.3.0
    - async-timeout==3.0.1
    - attrdict==2.0.1
    - attrs==19.3.0
    - autobahn==20.3.1
    - automat==20.2.0
    - base58==2.0.0
    - cachetools==4.0.0
    - cffi==1.14.0
    - cfgv==3.1.0
    - chardet==3.0.4
    - coincurve==13.0.0
    - constantly==15.1.0
    - cryptography==2.8
    - cytoolz==0.10.1
    - dateparser==0.7.4
    - decorator==4.4.2
    - deprecated==1.2.7
    - distlib==0.3.0
    - entrypoints==0.3
    - eth-abi==2.1.1
    - eth-account==0.4.0
    - eth-bloom==1.0.3
    - eth-hash==0.2.0
    - eth-keyfile==0.5.1
    - eth-keys==0.2.4
    - eth-rlp==0.1.2
    - eth-typing==2.2.1
    - eth-utils==1.8.4
    - filelock==3.0.12
    - flake8==3.7.9
    - future==0.18.2
    - hexbytes==0.2.0
    - hyperlink==19.0.0
    - identify==1.4.11
    - idna==2.9
    - incremental==17.5.0
    - ipfshttpclient==0.4.12
    - jsonschema==3.2.0
    - kafka-python==1.4.6
    - lru-dict==1.1.6
    - mccabe==0.6.1
    - multiaddr==0.0.9
    - multidict==4.7.5
    - mypy-extensions==0.4.3
    - netaddr==0.7.19
    - nodeenv==1.3.5
    - parsimonious==0.8.1
    - pefile==2019.4.18
    - pre-commit==2.1.1
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.5.0
    - pycparser==2.20
    - pycryptodome==3.9.7
    - pyflakes==2.1.1
    - pyhamcrest==2.0.2
    - pyinstaller==3.6
    - pyjwt==1.7.1
    - pyopenssl==19.1.0
    - pyperclip==1.7.0
    - pypiwin32==223
    - pyrsistent==0.15.7
    - python-binance==0.7.1
    - python-telegram-bot==12.4.2
    - pywin32==227
    - pywin32-ctypes==0.2.0
    - pyyaml==5.3
    - regex==2020.2.20
    - requests==2.23.0
    - rlp==1.2.0
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - service-identity==18.1.0
    - stringcase==1.2.0
    - toml==0.10.0
    - toolz==0.10.0
    - tornado==6.0.4
    - twisted==19.10.0
    - txaio==20.1.1
    - urllib3==1.25.8
    - varint==1.0.2
    - virtualenv==20.0.8
    - web3==5.5.1
    - websockets==8.1
    - wrapt==1.12.0
    - yarl==1.4.2
    - zope-interface==4.7.1
    - git+https://github.com/CoinAlpha/python-signalr-client.git
    - https://hummingbot-python.s3-us-west-2.amazonaws.com/hummingsim-20200308-cp38-cp38-win_amd64.whl
prefix: C:\Users\marti\Anaconda3\envs\hummingbot
