name: hummingbot-development
channels:
  - conda-forge
  - defaults
dependencies:
  ### Packages needed for the build/install process
  - coverage>=5.5
  # - cython=0.29.24
  - flake8>=3.7.9
  - diff-cover>=5.1.2
  - nose>=1.3.7
  - nose-exclude
  - pip>=21.1.2
  - pre-commit>=2.18.1
  - python>=3.10,<3.11
  - pytest>=4.6.11
  - setuptools>=50.3.2
  ### Packages used within HB and helping reduce the footprint of pip-installed packages
  - aiohttp>=3.8.4
  - aiokafka>=0.7.1
  - asyncssh>=2.7.2
  - aiounittest>=1.4.1
  - bidict
  - cryptography>=2.8
  - cachetools>=4.1.0
  - numpy>=1.20.1
  - numpy-base>=1.20.1
  - pandas>=1.2.1
  - pandas-ta>=0.3.14b0
  - prompt_toolkit>=3.0.20
  - protobuf>=4.21.0
  - psutil>=5.7.2
  - ptpython>=3.0.20
  - pydantic>=1.10.4
  - pyperclip>=1.7.0
  - requests>=2.28.2
  - ruamel.yaml>=0.16.10
  - scipy>=1.6.2
  - six>=1.14.0
  - sqlalchemy>=1.4,<1.4.99
  - tabulate>=0.8.9
  - ujson>=1.35
  - websockets>=9.1
  - yaml
  - zlib>=1.2.11
  ### Packages required by pip packages that are available on conda-forge/defaults
  #
  ## Packages for commlib-py
  - hiredis>=2.1.1
  - paho-mqtt>=1.6.1
  - pika>=1.3.1
  #
  ## Packages for docker
  - websocket-client>=1.5.1
  #
  ### Packages for dydx-v3-python - Need to make sure we don't require a package that creates a fictitious conflict
  - backports.zoneinfo>=0.2.1
  - base58>=2.1.1
  - dateparser>=1.0.0
  - ecdsa>=0.18.0
  - eth-account>=0.5.9
  - importlib-resources>=5.12.0
  - ipfshttpclient>=0.8.0a2
  - jsonschema>=4.13.0
  - lru-dict>=1.1.8
  - mpmath>=1.0.0
  - pkgutil-resolve-name>=1.3.10
  - pyrsistent>=0.18.0
  - sympy=>1.6.2
  # This creates major conflicts and long resolution time
  - web3>=5.31.4
  #
  ## Packages for ethsnarks-loopring
  - bitstring>=4.0.1
  - pyblake2>=1.1.2
  #
  ## Packages for injective-py
  - aiocron>=1.8
  - asn1crypto>=1.5.1
  - grpcio>=1.53.0
  - grpcio-tools>=1.53.0
  - mnemonic>=0.20
  #
  ## Packages for python-telegram-bot
  - future>=0.18.3
  - tornado>=6.2
  #
  ### Packages required by pip packages that are not available on conda-forge/defaults
  ### These are installed via pip --no-deps to prevent them overriding the conda
  ### packages above (see pip_packages.txt file).
  ### Some care was taken to include as many conda packages as possible
  ### to reduce the number of pip-installed packages.
  - pip:
    - git+https://github.com/CoinAlpha/python-signalr-client.git
    # - git+https://github.com/robotics-4-all/commlib-py.git@master